media: 
    input: public
    output: /
content:
  - name: cities
    label: Города
    type: collection
    path: src/content/cities
    filename:true
    view:
      fields: [title]
    fields:
      - { name: title, label: Заголовок на странице, type: sting }
  - name: services
    label: Сервисы
    type: collection
    path: src/content/services
    subfolders: true
    filename: true
    view:
      fields: [title]
    fields:
      - { name: title, label: Заголовок на странице, type: sting }